name: Reverse_engineeering
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h4b0e54e_0
  - brotli-python=1.0.9=py312h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.16.0=h85cdd14_6
  - certifi=2025.11.12=pyhd8ed1ab_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - eigen=3.4.0=h59b6b97_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.55.3=py312h827c3e9_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - joblib=1.4.2=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - kiwisolver=1.4.8=py312h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libprotobuf=5.29.3=h65a231f_1
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.0=py312haa95532_0
  - matplotlib-base=3.10.0=py312he19b0ae_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - numexpr=2.11.0=py312hdb065b2_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - onnx=1.18.0=np20py312h39c2283_0
  - opencv=4.10.0=py312h28596fa_7
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.6.0=h725018a_0
  - packaging=24.2=py312haa95532_0
  - pandas=2.3.2=py312ha5e6156_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py312hea0d53e_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h2bbff1b_1
  - protobuf=5.29.3=py312h275cf98_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyqt=6.7.1=py312h5da7b33_1
  - pyqt6-sip=13.9.1=py312h827c3e9_1
  - python=3.12.11=h716150d_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=2_cp312
  - pytz=2025.2=py312haa95532_0
  - qtbase=6.7.3=h0804d20_0
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - scikit-learn=1.6.1=py312h585ebfc_0
  - scipy=1.15.3=py312h180bac5_0
  - setuptools=78.1.1=py312haa95532_0
  - sip=6.10.0=py312h5da7b33_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tk=8.6.14=h5e9d12e_1
  - tornado=6.5.1=py312h827c3e9_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py312h827c3e9_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anomalib==2.2.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - attrs==25.4.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - docstring-parser==0.17.0
      - einops==0.8.1
      - filelock==3.13.1
      - freia==0.2
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - imagecodecs==2025.11.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - jsonargparse==4.44.0
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.3
      - numba==0.62.1
      - omegaconf==2.3.0
      - propcache==0.4.1
      - pygments==2.19.2
      - pytorch-lightning==2.6.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-argparse==1.7.2
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - shap==0.48.0
      - shellingham==1.5.4
      - slicer==0.0.8
      - sympy==1.13.3
      - tifffile==2025.12.12
      - timm==1.0.22
      - torch==2.8.0+cu126
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu126
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typeshed-client==2.8.2
      - typing-extensions==4.12.2
      - urllib3==2.6.2
      - yarl==1.22.0
prefix: C:\Users\hr73\.conda\envs\Reverse_engineeering
